# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:7.1.1-jdk16

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=true"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - deploy

core:
  stage: build
  script:
    - cd project/
    - gradle :core:build --build-cache
  cache:
    key: "$CI_JOB_STAGE"
    policy: push
    paths:
      - build/
      - project/build/
      - project/core/build/
      - project/desktop/build/
      - .gradle/

desktop:
  stage: build
  script:
    - cd project/
    - gradle :desktop:build --build-cache
  cache:
    key: "$CI_JOB_STAGE"
    policy: push
    paths:
      - build/
      - project/build/
      - project/core/build/
      - project/desktop/build/
      - .gradle/

test:
  stage: test
  script:
    - cd project/
    - gradle :test --build-cache
  cache:
    key: "$CI_JOB_STAGE"
    policy: pull
    paths:
      - build/
      - project/build/
      - project/core/build/
      - project/desktop/build/
      - .gradle/

deploy_doc:
  stage: deploy
  script:
    - cd project/
    - gradle :javadoc --build-cache
  cache:
    key: "$CI_JOB_STAGE"
    policy: push
    paths:
      - build/
      - project/build/
      - project/core/build/
      - project/desktop/build/
      - .gradle/
  artifacts:
    paths:
      - project/core/build/docs/javadoc/index.html
      - project/desktop/build/docs/javadoc/index.html
  rules:
    - if: '$CI_COMMIT_TITLE =~ /^.Merge./'
      when: on_success

deploy_install:
  stage: deploy
  script:
    - cd project/
    - gradle :desktop:installDist --build-cache
  cache:
    key: "$CI_JOB_STAGE"
    paths:
      - build/
      - project/build/
      - project/core/build/
      - project/desktop/build/
      - .gradle/
  rules:
    - if: '$CI_COMMIT_TITLE =~ /^.Merge./'
      when: on_success
